apiVersion: apps/v1
kind: Deployment
metadata:
   name: devops-final-exam-deployment
spec:
  replicas: 3
  selector:
     matchLabels:
      app: devops-final-exam-deployment
  template:
     metadata:
       labels:
         app:devops-final-exam
     spec:
      containers:
      - name : devops-final-exam-container
        image: arshdeepsingh070/devops-final-exam:latest   
        ports:
         - containerPort : 8080
---
apiVersion: v1
kind: Service
metadata:
   name: devops-final-exam-Service
spec:
  selector: 
    app: devops-final-exam-deployment
    
    ports:
    - port: 8080
      targetPort: 8080  
    type: LoadBalancer      
     