apiVersion: apps/v1

kind: Deployment
metadata:
   name: devops-exam-practice
spec: 
   replicas: 3
   selector:
     matchLabels:
       app: devops-exam-practice
       
   template:
     metadata:
       labels:
         app: devops-exam-practice
            
     spec:
       containers:
       - name: devops-pratice-container
         image: arshdeepsingh070/devops-final-exam:latest
         ports:
         - containerPort: 8080

---
kind: service
appVersion: v1
metadata:
   name: devops-exam-practice
spec:
  type: NodePort
  selector:
     app: devops-practice-container
  ports:
  - protocol : TCP
    nodeport: 30157  
    port: 8080
    targetPort: 8080            